### PR TITLE
Add integration tests with travis

### PR DESCRIPTION
**Pull request by erbriones**
Add travis support for running robot framework tests.

This will add a build status to the main README file. 
screen shot 2017-02-01 at 8 44 25 pm

After configuring travis the tests will be automatically run. This will be triggered by changes on the master branch and external pull requests 
screen shot 2017-02-01 at 8 46 00 pm

### CODE REVIEW

**Comment by erbriones** [comment]
The token in the tests should probably be removed from resources.robot and set as an environment variable in travis.

**Comment by erbriones** [comment]
I'm still looking how to fix the HTTPS warning message from being shown.

**Comment by erbriones** [comment]
I've created a separate pull request to solve the warnings [here](https://github.com/LyonsLab/coge/pull/74)

**Comment by mbomhoff** [comment]
Hey Evan, I'm not interested in using this.  You'll be testing against a sandbox on GECO.

**Comment by erbriones** [comment]
Okay, I just thought it would be an easy way to automatically run tests against the sandbox.

**Comment by mbomhoff** [comment]
I want our test process to be independent of third-party platforms.  That's a cool service you found, but we will be running the tests manually as needed.  With only two developers it's easier that way.  The SSL fixes are nice, I will merge those changes.

**Comment by erbriones** [comment]
Sounds good. I'll just this here for historical reference.

**Pull request closed without merging**
